# Generated by Django 3.1.1 on 2020-10-13 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_productreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='productreview',
            name='stars',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productreview',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product'),
        ),
    ]
